apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
        - name: tenant
          image: hishampaloli/tenant
          env:
            - name: MONGO_URL
              value: "mongodb+srv://hishampaloli:hisham@tenant.w89pd3z.mongodb.net/"
            - name: TWILIO_ACC_SID
              value: "ACc6812664b3f21c5c669509cff5764bb9"
            - name: TWILIO_TOKEN_AUTH
              value: "17bd53cdd16abf02341b7b1d92ac7354"
            - name: TWILIO_SERVICE_SID
              value: "VA5597e0ac8e160a7236be137d237e034e"            
            - name: EMAIL_STR
              value: "perilla.hrservice@gmail.com"
            - name: PASSWORD_STR
              value: "cglzqvagkozftaco"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: tenant-srv
spec:
  selector:
    app: tenant
  ports:
    - name: tenant
      protocol: TCP
      port: 3000
      targetPort: 3000
