name: tests-tenant

on: 
  pull_request:
    paths:
      - 'tenant/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tenant && npm install
