name: tests-resource

on: 
  pull_request:
    paths:
      - 'resource/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd resource && npm install
